language: r

cache: false
latex: false

before_script:
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

script: 
  - R -f tests/render_rmds.R


addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libgdal-dev 
      - libgeos-dev 
      - libudunits2-dev 
      - libv8-dev 
      - libjq-dev 
      - libprotobuf-dev 
      - protobuf-compiler
      - libssl-dev
      - libcairo2-dev
      - libnetcdf-dev
      - netcdf-bin
