language: r

sudo: required
dist: trusty
cache: false
latex: false


addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev 
      - libgeos-dev 
      - libproj-dev 
      - libudunits2-dev 
      - libv8-dev 
      - libjq-dev 
      - libprotobuf-dev 
      - protobuf-compiler
      - libssl-dev
      - libcairo2-dev
      - libnetcdf-dev
      - netcdf-bin
      
script: 
  - R -f tests/render_rmds.R

